---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-node-deployment
  labels:
    app: nginx-node
  namespace: default
spec:
  replicas: 3
  selector:
    matchLabels:
      app: nginx-node
  template:
    metadata:
      labels:
        app: nginx-node
    spec:
      containers:
      - name: nginx-node
        image: nginx:1.14.2
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 80
      - name: multitool
        image: wbitt/network-multitool
        imagePullPolicy: IfNotPresent
        env:
          - name: HTTP_PORT 
            value: "8080"
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: nginx-node-svc
spec:
  selector:
    app: nginx-node
  ports:
  - name: ngixn-port
    protocol: TCP
    nodePort: 9001
    port: 80
  - name: multitool-port
    protocol: TCP
    nodePort: 9002
    port: 8080
  type: NodePort
...