---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: pod-info
rules:
- apiGroups: [""]
  resources: ["pods/log"]
  verbs: ["get", "watch"]
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["get", "list", "watch"]
...
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: pod-info-rolebinding
subjects:
- kind: User
  name: netology-user
  apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: Role
  name: pod-info
  apiGroup: rbac.authorization.k8s.io
...
