---
apiVersion: v1
kind: Pod
metadata:
  name: multitool-web
  labels:
    app: multitool
spec:
  containers:
  - name: multitool
    image: wbitt/network-multitool
    imagePullPolicy: IfNotPresent
    env:
      - name: HTTP_PORT 
        value: "8082"
    ports:
    - containerPort: 8082
...