---
apiVersion: v1
kind: Pod
metadata:
  name: netology-web
  labels:
    app: myapp
spec:
  containers:
  - name: netology
    image: gcr.io/kubernetes-e2e-test-images/echoserver:2.2
    ports:
    - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: netology-svc
spec:
  selector:
    app: myapp
  ports:
  - name: web
    protocol: TCP
    port: 8080
    targetPort: 8080
...