apiVersion: v1
clusters:
- cluster:
    certificate-authority-data: 
    server: https://158.160.17.123:16443
  name: microk8s-cluster
contexts:
- context:
    cluster: microk8s-cluster
    user: admin
  name: microk8s
current-context: microk8s
kind: Config
preferences: {}
users:
- name: admin
  user:
    token: 