---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-https-deployment
  labels:
    app: nginx-https
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx-https
  template:
    metadata:
      labels:
        app: nginx-https
    spec:
      containers:
      - name: nginx-https
        image: nginx:1.14.2
        imagePullPolicy: IfNotPresent
        resources:
          limits:
            memory: 1024Mi
            cpu: "2"
          requests:
            memory: 512Mi
            cpu: "1"
        volumeMounts:
        - name: configmap-volume
          mountPath: /usr/share/nginx/html
        ports:
        - containerPort: 80
        - containerPort: 443
      - name: multitool-https
        image: wbitt/network-multitool
        imagePullPolicy: IfNotPresent
        resources:
          limits:
            memory: 1024Mi
            cpu: "2"
          requests:
            memory: 512Mi
            cpu: "1"
        env:
          - name: HTTP_PORT 
            valueFrom:
              configMapKeyRef:
                name: my-configmap
                key: http_port
        ports:
        - containerPort: 8080
        volumes:
        - name: configmap-volume
          configMap:
            name: my-configmap
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: my-configmap
  namespace: default
data:
  http_port: "8080"
  index.html: |
    <!DOCTYPE html>
    <html>
    <head>
    <title>Hello Netology!</title>
    <style>
        body {
            width: 35em;
            margin: 0 auto;
            font-family: Tahoma, Verdana, Arial, sans-serif;
        }
    </style>
    </head>
    <body>
    <h1>>Hello Netology!</h1>
    <p>If you see this page, than I configured my own nginx server.</p>

    <p><em>Thank you for your classes.</em></p>
    </body>
    </html>


---
apiVersion: v1
kind: Service
metadata:
  name: nginx-https-svc
spec:
  selector:
    app: nginx-https
  ports:
  - name: nginx-http-port
    protocol: TCP
    nodePort: 30080
    port: 80
  - name: nginx-https-port
    protocol: TCP
    nodePort: 30443
    port: 443
  - name: multitool-http-port
    protocol: TCP
    nodePort: 30880
    port: 8080
  type: NodePort
# ---
# apiVersion: networking.k8s.io/v1
# kind: Ingress
# metadata:
#   name: myingress
#   annotations:
#     nginx.ingress.kubernetes.io/rewrite-target: /
#   labels:
#     name: myingress
# spec:
#   rules:
#   - host: 
#     http:
#       paths:
#       - path: /
#         pathType: Prefix
#         backend:
#           service:
#             name: nginx-https-svc
#             port:
#               name: nginx-http-port