---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
  labels:
    app: nginx
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: nginx:1.14.2
        imagePullPolicy: IfNotPresent
        resources:
          limits:
            memory: 1024Mi
            cpu: "2"
          requests:
            memory: 512Mi
            cpu: "1"
        ports:
        - containerPort: 80
      - name: multitool
        image: wbitt/network-multitool
        imagePullPolicy: IfNotPresent
        resources:
          limits:
            memory: 1024Mi
            cpu: "2"
          requests:
            memory: 512Mi
            cpu: "1"
        env:
          - name: HTTP_PORT 
            valueFrom:
              configMapKeyRef:
                name: my-configmap
                key: http_port
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: my-configmap
  namespace: default
data:
  http_port: "8080"

---
apiVersion: v1
kind: Service
metadata:
  name: nginx-node-svc
spec:
  selector:
    app: nginx
  ports:
  - name: ngixn-port
    protocol: TCP
    nodePort: 30001
    port: 80
  - name: multitool-port
    protocol: TCP
    nodePort: 30002
    port: 8080
  type: NodePort